name: docker-release-rust-tools
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
env:
  REGISTRY: docker.io
  IMAGE_NAME: segmeter

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: extract version
      #   id: extract_version
      #   run: |
      #     VERSION=${GITHUB_REF#refs/tags/}
      #     echo "::set-output name=VERSION::$VERSION"

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          # tags: yanglabinfo/segmeter:${{ steps.extract_version.outputs.VERSION }}, yanglabinfo/segmeter:latest
          tags: yanglabinfo/segmeter:latest
