name: docker-release-giggle
on:
  push:
    tags:
      - "*"
env:
  REGISTRY: docker.io
  IMAGE_NAME: segmeter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./containers/giggle/Dockerfile
          platforms: linux/amd64
          #, linux/arm64
          push: true
          memory: 4G
          tags: |
            yanglabinfo/segmeter:giggle-main
            yanglabinfo/segmeter:giggle-latest
